/**
 * Extracted verbatim from the osint-synthesis-engine repository's committed
 * demo/prerecorded_responses.json. These are saved outputs of real agent runs
 * (recorded 2026-09-18), replayed unchanged. Nothing here calls the backend.
 */
export const osintDemo = {
  "notice": "PRERECORDED RESPONSE: this report was generated by a real run of the agent (retrieval + LLM) on 2026-09-18 and saved. It is replayed unchanged; it was not generated for your request.",
  "model": "openai/gpt-oss-120b",
  "responses": [
    {
      "query": "cryptocurrency exchange with prior AML compliance actions and sanctions exposure",
      "recordedAt": "20260918",
      "report": "**OSINT Structured Report – Cryptocurrency‑Related Entities with Prior AML‑Compliance Actions and Sanctions Exposure**  \n\n---\n\n### 1. Scope & Methodology  \n- **Entity category examined:** Organizations that operate in the cryptocurrency ecosystem (e.g., custodians, sponsors, market‑makers, prime brokers) and that have documented AML (Anti‑Money‑Laundering) or sanctions‑related regulatory actions.  \n- **Source material:** Five public‑record excerpts extracted from SEC EDGAR filings (see “RETRIEVED PUBLIC‑RECORD EXCERPTS”).  \n- **Approach:** Each excerpt was read verbatim; factual statements were extracted and attributed to the corresponding excerpt number. No external information or speculation was added. Where the excerpts do not address a particular aspect of the profile, this is noted explicitly.\n\n---\n\n### 2. Key Findings  \n\n| Topic | What the excerpts state | Source |\n|-------|------------------------|--------|\n| **Existence of AML / sanctions compliance programs** | • The Bitcoin Custodian (the entity that holds the underlying BTC for the Invesco Galaxy Bitcoin ETF) “has adopted and implemented an anti‑money laundering and sanctions compliance program” intended to prevent transactions with sanctioned parties. <br>• The Sponsor, the Execution Agent, and the Trust have also “adopted and implemented policies and procedures … designed to ensure that they do not violate applicable AML and sanctions laws and regulations.” | [1], [2] |\n| **Regulatory risk language** | The Trust’s registration statement includes a risk factor titled **“Anonymity and illicit financing risk.”** The filing explains that inadequate AML/sanctions controls by any of the parties (Authorized Participants, Market Makers, Bitcoin Custodian, Prime Broker) could lead to violations and regulatory liability (fines, penalties, other punishments). | [4] |\n| **Potential liability for AML/sanctions failures** | The filing explicitly states that violations could result in “regulatory liability for the Trust, the Sponsor, the Trustee or their affiliates … including governmental fines, penalties, and other punishments.” | [4] |\n| **Historical enforcement actions against financial institutions (non‑crypto)** | • **AmSouth Bancorporation** was found by FinCEN to have “willfully violated the anti‑money laundering program and suspicious activity reporting requirements of the Bank Secrecy Act.” <br>• **American Express (AEBI)** received DOJ, Federal Reserve, and FinCEN notices in 2006‑2007 concerning “potential enforcement actions relating to its AML programs.” | [3], [5] |\n| **Supervisory oversight** | • AmSouth’s AML compliance is examined by the **Board of Governors of the Federal Reserve System**, which is its primary federal supervisory agency. <br>• The same Federal Reserve and FinCEN also communicated AML concerns to American Express. | [3], [5] |\n| **Reference to “Bitcoin Custodian” as a key AML actor** | The custodian is singled out as a party whose AML and sanctions controls are critical to the overall compliance posture of the ETF structure. | [1], [4] |\n| **No explicit mention of a cryptocurrency exchange** | None of the excerpts identify a crypto‑exchange (i.e., a platform that matches buyers and sellers of digital assets) nor describe AML actions taken *against* such an exchange. | — |\n\n---\n\n### 3. Assessment of AML / Sanctions Exposure for the Investigated Category  \n\n1. **Programmatic Controls Exist** – The documents confirm that the Bitcoin Custodian, Sponsor, Execution Agent, and other service providers have formal AML and sanctions compliance programs in place. This satisfies a baseline regulatory expectation for entities handling crypto assets in the United States.  \n\n2. **Regulatory Risk Acknowledged** – The inclusion of a specific risk factor (“Anonymity and illicit financing risk”) and the language about possible fines/penalties demonstrate that the filing parties recognize the heightened AML/sanctions risk inherent to crypto‑related products.  \n\n3. **Potential for Liability is Explicitly Stated** – The filings warn that any deficiency in the AML/sanctions controls of the listed participants could expose the Trust and its affiliates to enforcement actions. This underscores that regulators may hold not only the primary custodian but also ancillary service providers accountable.  \n\n4. **Historical Enforcement Context** – While the excerpts do not detail AML violations by a crypto exchange, they do provide concrete examples of traditional financial institutions (AmSouth, American Express) that have faced FinCEN or DOJ enforcement for AML deficiencies. This illustrates that the regulatory environment is actively monitoring and penalizing AML shortcomings across the financial sector, including entities that interact with crypto assets.  \n\n5. **Supervisory Oversight** – The Federal Reserve’s role as primary supervisor for AmSouth, and its involvement (alongside FinCEN) in the American Express matter, indicates that U.S. banking regulators are a key point of contact for AML compliance, even when the underlying activity involves crypto‑related services.  \n\n---\n\n### 4. Information Gaps  \n\n| Aspect of Profile | Availability in the excerpts | Comment |\n|-------------------|------------------------------|---------|\n| **Specific AML violations or enforcement actions taken against a cryptocurrency exchange** | **Not present** | No excerpt mentions a crypto exchange being fined, sanctioned, or otherwise penalized. |\n| **Details of the AML program (e.g., transaction monitoring thresholds, SAR filing frequency, sanctions screening vendors)** | **Not present** | The filings only state that a program “has been adopted and implemented” without technical specifics. |\n| **Identity or jurisdiction of the “Bitcoin Custodian”** | **Not present** | The custodian is referenced generically; no name, location, or licensing information is provided. |\n| **Direct linkage between the cited traditional‑bank enforcement actions and crypto‑exchange compliance** | **Not present** | The AmSouth and American Express cases involve conventional banking activities; no explicit connection to crypto‑exchange operations is made. |\n| **Any subsequent remediation or corrective actions taken after the cited enforcement notices** | **Not present** | The excerpts do not describe post‑violation remediation steps. |\n\n---\n\n### 5. Conclusions  \n\n- The excerpts collectively demonstrate that entities participating in a U.S.‑listed Bitcoin ETF (custodian, sponsor, execution agent, market makers, prime broker) are required to maintain AML and sanctions compliance programs and are aware of the regulatory risks associated with crypto‑related anonymity and illicit financing.  \n- The filings explicitly warn that deficiencies in these programs could trigger regulatory liability, including fines and penalties.  \n- Historical enforcement actions against non‑crypto financial institutions (AmSouth, American Express) illustrate that U.S. regulators actively enforce AML obligations and that similar scrutiny could be applied to crypto‑exchange operators, even though the current excerpts do not provide a concrete example of such an enforcement action.  \n- Because the source material does not contain any direct reference to a cryptocurrency exchange or to AML/sanctions violations specific to an exchange, the report cannot confirm the existence of prior AML compliance actions or sanctions exposure for that particular sub‑category. Further research using additional filings, sanction lists, or enforcement databases would be required to fill those gaps.  \n\n---  \n\n*Prepared by: OSINT Analyst*  \n*Date: 2026‑09‑18*",
      "citations": [
        "sec-edgar-0001193125-23-294476:filename1.htm",
        "sec-edgar-0000891836-04-000358:ex_99-4.htm",
        "sec-edgar-0001104659-07-059276:a07-21089_28k.htm"
      ],
      "tokenUsage": {
        "input_tokens": 966,
        "output_tokens": 1693,
        "reasoning_tokens": 169,
        "total_tokens": 2659,
        "latency_seconds": 4.07
      },
      "sources": [
        {
          "index": 1,
          "docId": "sec-edgar-0001193125-23-294476:filename1.htm",
          "source": "SEC_EDGAR",
          "title": "CORRESP — Invesco Galaxy Bitcoin ETF  (BTCO)  (CIK 0001855781)",
          "url": "https://www.sec.gov/Archives/edgar/data/1855781/000119312523294476/filename1.htm",
          "excerpt": ". Bank Secrecy Act (as amended) (“BSA”) and U.S. economic sanctions laws. The Bitcoin Custodian has adopted and implemented an anti-money laundering and sanctions compliance program that provides protections intended to ensure that the Sponsor and the Trust do not transact with a sanctioned party",
          "cited": true
        },
        {
          "index": 2,
          "docId": "sec-edgar-0001193125-23-294476:filename1.htm",
          "source": "SEC_EDGAR",
          "title": "CORRESP — Invesco Galaxy Bitcoin ETF  (BTCO)  (CIK 0001855781)",
          "url": "https://www.sec.gov/Archives/edgar/data/1855781/000119312523294476/filename1.htm",
          "excerpt": ". 2 Response : The following descriptions of the relevant Anti-Money Laundering and Know Your Customer (“AML/KYC”) policies and procedures has been added to the Trust’s Registration Statement under the risk factor titled “ Anonymity and illicit financing risk” : The Sponsor, the Execution Agent and the Trust have adopted and implemented policies and procedures that are designed to ensure that they do not violate applicable AML and sanctions laws and regulations and to comply with any applicable",
          "cited": true
        },
        {
          "index": 3,
          "docId": "sec-edgar-0000891836-04-000358:ex_99-4.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — AMSOUTH BANCORPORATION  (CIK 0000003133)",
          "url": "https://www.sec.gov/Archives/edgar/data/3133/000089183604000358/ex_99-4.htm",
          "excerpt": ". The Board of Governors of the Federal Reserve System (the “Federal Reserve”) is AmSouth’s primary federal supervisory agency and examines AmSouth for Bank Secrecy Act compliance. III. FINCEN’S DETERMINATIONS A. Summary of Violations FinCEN has determined that AmSouth willfully violated the anti-money laundering program and suspicious activity reporting requirements of the Bank Secrecy Act and its implementing regulations",
          "cited": true
        },
        {
          "index": 4,
          "docId": "sec-edgar-0001193125-23-294476:filename1.htm",
          "source": "SEC_EDGAR",
          "title": "CORRESP — Invesco Galaxy Bitcoin ETF  (BTCO)  (CIK 0001855781)",
          "url": "https://www.sec.gov/Archives/edgar/data/1855781/000119312523294476/filename1.htm",
          "excerpt": ". If the Authorized Participants, the Market Makers, the Bitcoin Custodian or the Prime Broker were to have inadequate policies, procedures and controls for complying with applicable anti-money laundering and applicable sanctions laws or the Trust’s diligence is ineffective, violations of such laws could result, which could result in regulatory liability for the Trust, the Sponsor, the Trustee or their affiliates under such laws, including governmental fines, penalties, and other punishments, as",
          "cited": true
        },
        {
          "index": 5,
          "docId": "sec-edgar-0001104659-07-059276:a07-21089_28k.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — AMERICAN EXPRESS CO  (AXP)  (CIK 0000004962)",
          "url": "https://www.sec.gov/Archives/edgar/data/4962/000110465907059276/a07-21089_28k.htm",
          "excerpt": ". In September 2006, the DOJ informed AEBI of concerns relating to its AML compliance program. In addition, in 2007, the Board of Governors of the Federal Reserve System (the “Federal Reserve”) and the Financial Crimes Enforcement Network (“FinCEN”) of the Department of Treasury informed AEBI of potential enforcement actions relating to its AML programs",
          "cited": true
        }
      ]
    },
    {
      "query": "crypto mixing service with links to sanctioned jurisdictions",
      "recordedAt": "20260918",
      "report": "**OSINT Structured Report – Crypto‑Mixing Service with Links to Sanctioned Jurisdictions**  \n*Entity Category under Investigation: “Crypto‑mixing service with links to sanctioned jurisdictions”*  \n\n---\n\n### 1. Scope of the Review  \nThe analysis is limited to the five public‑record excerpts supplied (labeled [1]–[5]). No external sources or speculative conclusions are used. All statements are directly traceable to the cited excerpts.\n\n---\n\n### 2. Summary of What the Excerpts State  \n\n| Topic | Statement Derived from the Excerpts | Source |\n|-------|--------------------------------------|--------|\n| **Business activities of Coincheck Group N.V.** | Coincheck conducts “cover transactions” on its exchange platform, either with customers directly or with external exchanges/market makers connected via API, to offset its own positions or reduce exposure arising from crypto‑asset transactions on its Marketplace platform. | [1], [2] |\n| **Service model terminology** | Coincheck (or a similar licensed provider) offers “Crypto‑as‑a‑Service” (CaaS), which includes white‑label or co‑branded arrangements that allow third‑party firms to obtain crypto‑asset trade execution, settlement, and/or custody from a licensed provider for B2B2C distribution. | [3] |\n| **Regulatory compliance language (general AML/ sanctions)** | The Bitcoin Custodian for the Invesco Galaxy Bitcoin ETF has adopted an anti‑money‑laundering (AML) and sanctions compliance program intended to prevent transactions with sanctioned parties, referencing the Bank Secrecy Act and U.S. economic sanctions laws. | [4] |\n| **Potential regulatory consequences for inadequate AML/sanctions controls** | If the Authorized Participants, Market Makers, Bitcoin Custodian, or Prime Broker lack adequate AML/sanctions policies, the Trust, Sponsor, Trustee, or affiliates could face regulatory liability, including fines, penalties, and other punishments. | [5] |\n\n---\n\n### 3. Direct Findings Relevant to the Investigated Category  \n\n| Finding | Evidence |\n|---------|----------|\n| **No explicit mention of a crypto‑mixing (tumblers) service** | None of the excerpts use the terms “mixing,” “tumbling,” “privacy‑enhancing service,” or describe a process that obscures transaction trails. | — |\n| **No explicit link to sanctioned jurisdictions** | The excerpts discuss compliance programs designed to *avoid* transactions with sanctioned parties (see [4]), but they do not state that the entities themselves have connections to or operate within sanctioned jurisdictions. | — |\n| **Reference to AML/sanctions compliance frameworks** | Both Coincheck’s filings ([1]–[3]) and the Invesco Galaxy Bitcoin ETF filings ([4]–[5]) highlight the existence of AML and sanctions compliance programs, indicating awareness of regulatory requirements. | [4], [5] |\n| **Operational model that could be leveraged for third‑party services** | The CaaS description in [3] indicates that a licensed crypto‑asset provider can supply trade execution, settlement, and custody services to other firms, which *could* be used to build downstream services (including, hypothetically, mixing services). However, the excerpt does not state that such downstream services are mixing services nor that they involve sanctioned jurisdictions. | [3] |\n\n---\n\n### 4. Gaps – Information Not Covered by the Excerpts  \n\n| Aspect of the Profile | Availability in the Provided Excerpts |\n|-----------------------|----------------------------------------|\n| **Explicit identification of a crypto‑mixing service** | No excerpt mentions a mixing/tumbling service. |\n| **Operational details of any mixing service (e.g., technology, transaction flow, fees)** | Not present. |\n| **Evidence of direct business relationships with entities located in sanctioned jurisdictions** | Not present. |\n| **Specific sanctions‑list matches or designations (e.g., OFAC, EU, UN)** | Not present. |\n| **Incidents of regulatory enforcement or penalties related to mixing activities** | Not present. |\n| **Customer onboarding or KYC/AML procedures specific to a mixing service** | Not present. |\n| **Geographic location of the service’s infrastructure (servers, wallets, etc.)** | Not present. |\n\n*When an excerpt does not provide the requested information, the report explicitly notes the absence rather than inferring or speculating.*\n\n---\n\n### 5. Conclusions  \n\n1. **The supplied excerpts describe the business model and regulatory compliance posture of Coincheck Group N.V. and the Invesco Galaxy Bitcoin ETF’s custodial arrangements.** They focus on “cover transactions,” Crypto‑as‑a‑Service offerings, and AML/sanctions compliance programs.  \n\n2. **There is no direct evidence within the provided excerpts that a crypto‑mixing service exists, nor that any such service is linked to sanctioned jurisdictions.**  \n\n3. **The only relevant information is the general emphasis on AML and sanctions compliance (see [4]–[5]), which indicates that the entities are aware of and seek to avoid prohibited transactions.** This does not imply the presence of prohibited activity.  \n\n4. **Significant gaps remain concerning the core investigative focus (mixing service operations and sanctioned‑jurisdiction links).** Additional sources would be required to assess whether any crypto‑mixing service operates under the umbrella of the entities mentioned, or whether any such service has ties to sanctioned jurisdictions.\n\n---  \n\n*Prepared solely from the supplied public‑record excerpts. No external data or speculation has been incorporated.*",
      "citations": [
        "sec-edgar-0001913847-25-000033:cnck6-kseptember2025conden.htm",
        "sec-edgar-0001193125-23-294476:filename1.htm",
        "sec-edgar-0001628280-26-009284:cnck-20251231_d2.htm",
        "sec-edgar-0001628280-26-057095:cnck6-kjune2026consolidate.htm"
      ],
      "tokenUsage": {
        "input_tokens": 1013,
        "output_tokens": 1237,
        "reasoning_tokens": 82,
        "total_tokens": 2250,
        "latency_seconds": 3.21
      },
      "sources": [
        {
          "index": 1,
          "docId": "sec-edgar-0001913847-25-000033:cnck6-kseptember2025conden.htm",
          "source": "SEC_EDGAR",
          "title": "424B3 — Coincheck Group N.V.  (CNCK, CNCKW)  (CIK 0001913847)",
          "url": "https://www.sec.gov/Archives/edgar/data/1913847/000191384725000033/cnck6-kseptember2025conden.htm",
          "excerpt": ". cover transactions Transactions executed by Coincheck on the Exchange platform with a customer, or with a party on an external exchange or market maker that is connected via API to Coincheck’s systems, in order to offset Coincheck’s own positions or reduce its exposure arising from transactions in crypto assets with customers using Coincheck’s Marketplace platform. crypto A broad term for any cryptography-based market, system, application, or decentralized network",
          "cited": true
        },
        {
          "index": 2,
          "docId": "sec-edgar-0001628280-26-009284:cnck-20251231_d2.htm",
          "source": "SEC_EDGAR",
          "title": "6-K — Coincheck Group N.V.  (CNCK, CNCKW)  (CIK 0001913847)",
          "url": "https://www.sec.gov/Archives/edgar/data/1913847/000162828026009284/cnck-20251231_d2.htm",
          "excerpt": ". cover transactions Transactions executed by Coincheck on the Exchange platform with a customer, or with a party on an external exchange or market maker that is connected via API to Coincheck’s systems, in order to offset Coincheck’s own positions or reduce its exposure arising from transactions in crypto assets with customers using Coincheck’s Marketplace platform. crypto A broad term for any cryptography-based market, system, application, or decentralized network",
          "cited": true
        },
        {
          "index": 3,
          "docId": "sec-edgar-0001628280-26-057095:cnck6-kjune2026consolidate.htm",
          "source": "SEC_EDGAR",
          "title": "6-K — Coincheck Group N.V.  (CNCK, CNCKW)  (CIK 0001913847)",
          "url": "https://www.sec.gov/Archives/edgar/data/1913847/000162828026057095/cnck6-kjune2026consolidate.htm",
          "excerpt": ". CaaS Crypto-as-a-Service, more specifically, white-label or co-branded offerings or similar distribution arrangements with third-party firms who need crypto-asset trade execution and settlement, and/or custody, from a licensed crypto-asset provider so that they may offer crypto asset investments to their customer bases, sometimes also referred to as a type of B2B2C (business-to-business-to-customer) relationship. CASP Crypto-assets services provider (as licensed by the AMF)",
          "cited": true
        },
        {
          "index": 4,
          "docId": "sec-edgar-0001193125-23-294476:filename1.htm",
          "source": "SEC_EDGAR",
          "title": "CORRESP — Invesco Galaxy Bitcoin ETF  (BTCO)  (CIK 0001855781)",
          "url": "https://www.sec.gov/Archives/edgar/data/1855781/000119312523294476/filename1.htm",
          "excerpt": ". Bank Secrecy Act (as amended) (“BSA”) and U.S. economic sanctions laws. The Bitcoin Custodian has adopted and implemented an anti-money laundering and sanctions compliance program that provides protections intended to ensure that the Sponsor and the Trust do not transact with a sanctioned party",
          "cited": true
        },
        {
          "index": 5,
          "docId": "sec-edgar-0001193125-23-294476:filename1.htm",
          "source": "SEC_EDGAR",
          "title": "CORRESP — Invesco Galaxy Bitcoin ETF  (BTCO)  (CIK 0001855781)",
          "url": "https://www.sec.gov/Archives/edgar/data/1855781/000119312523294476/filename1.htm",
          "excerpt": ". If the Authorized Participants, the Market Makers, the Bitcoin Custodian or the Prime Broker were to have inadequate policies, procedures and controls for complying with applicable anti-money laundering and applicable sanctions laws or the Trust’s diligence is ineffective, violations of such laws could result, which could result in regulatory liability for the Trust, the Sponsor, the Trustee or their affiliates under such laws, including governmental fines, penalties, and other punishments, as",
          "cited": true
        }
      ]
    },
    {
      "query": "money services business with prior consent order for AML violations",
      "recordedAt": "20260918",
      "report": "**OSINT Structured Report – Money‑Services‑Business (MSB) / Banking Entities with Prior Consent Orders for AML Violations**  \n\n---\n\n### 1. Scope of the Source Material  \nThe excerpts are taken from U.S. Securities and Exchange Commission (SEC) Form 8‑K filings for two publicly‑traded banking groups:\n\n| Entity | Filing Identifier | Primary Documents Referenced |\n|--------|-------------------|------------------------------|\n| **AmSouth Bancorporation** | CIK 0000003133 | Excerpts [1] and [4] |\n| **Fulton Financial Corporation** | CIK 0000700564 | Excerpts [2], [3] and [5] |\n\nAll excerpts discuss **consent‑order actions** issued by U.S. banking regulators (FinCEN and the Office of the Comptroller of the Currency – OCC) that relate to deficiencies in the entities’ **Bank Secrecy Act / Anti‑Money‑Laundering (BSA/AML) compliance programs**.\n\n---\n\n### 2. Regulatory Findings – What the Excerpts State  \n\n| Finding | Evidence |\n|---------|----------|\n| **Existence of a consent‑order/cease‑and‑desist order** for AML‑related deficiencies. | AmSouth entered a “combined consent Cease and Desist Order and Order of Assessment of a Civil Money Penalty” [1]; Fulton’s subsidiaries entered “Stipulation and Consent to the Issuance of a Consent Order” with the OCC [2], [3]. |\n| **Specific regulatory bodies involved**: <br>• Financial Crimes Enforcement Network (FinCEN) – for AmSouth [4] <br>• Office of the Comptroller of the Currency (OCC) – for Fulton’s subsidiaries [2], [3] | Direct references to FinCEN’s determinations [4] and OCC’s issuance of Consent Orders [2], [3]. |\n| **Areas of deficiency identified** (as enumerated by the regulators): <br>• AML policies and procedures <br>• Customer due‑diligence practices <br>• Fraud‑detection program <br>• Internal control environment <br>• Management oversight <br>• Responses to law‑enforcement and regulatory requests | Listed in the AmSouth excerpt [1]; the Fulton excerpts reference “BSA/AML Requirements and the BSA/AML Compliance Program” [2], [3]. |\n| **Date of the consent actions** (where provided): <br>• AmSouth’s civil‑money‑penalty consent dated **October 12 2004** [4] <br>• Fulton’s subsidiaries’ consent actions dated **July 14 2014** [2], [3] | Explicit dates in the respective excerpts. |\n| **Nature of the consent** – entities **did not admit or deny** the regulator’s findings (except limited jurisdictional admissions). | AmSouth’s filing states the consent was entered “without admitting or denying FinCEN’s determinations … except as to jurisdiction” [4]. |\n| **Potential for additional enforcement** – Fulton’s filing notes that other subsidiary banks **may also become subjects of regulatory enforcement** and that any such actions could differ from the existing consent orders. | Stated in excerpt [5]. |\n| **Financial consequence** – AmSouth agreed to an **assessment of a civil money penalty** (amount not disclosed in the excerpts). | Mentioned in excerpt [4] (“Assessment of Civil Money Penalty”). |\n| **Joint compliance program** – Fulton’s subsidiaries operate a **single BSA/AML compliance program** across all banks, meaning a breach in one can affect the others. | Described in excerpt [5]. |\n\n---\n\n### 3. Summary of the Consent‑Order Process (as reflected in the excerpts)\n\n| Step | Description (as per excerpts) |\n|------|--------------------------------|\n| **Regulatory Investigation** | Regulators identified deficiencies in AML‑related controls (customer due‑diligence, fraud detection, internal controls, etc.) [1]. |\n| **Negotiated Settlement** | The institutions entered into a **Stipulation and Consent** (Fulton) or **Consent to the Assessment of a Civil Money Penalty** (AmSouth) to resolve the matter without admitting liability [4]. |\n| **Formal Order Issuance** | A **Cease and Desist Order** (AmSouth) or **Consent Order** (Fulton) was issued, mandating corrective actions and ongoing oversight [1], [2], [3]. |\n| **Penalty Assessment** | AmSouth’s consent includes an **assessment of a civil money penalty** (amount unspecified) [4]. |\n| **Future Enforcement Risk** | Fulton’s filing acknowledges that other subsidiaries could face separate enforcement actions, potentially with different terms [5]. |\n\n---\n\n### 4. Gaps & Information Not Provided in the Excerpts  \n\n| Aspect | Missing Information |\n|--------|----------------------|\n| **Exact monetary amount** of the civil money penalty assessed against AmSouth. | Not disclosed in excerpt [4]. |\n| **Specific remedial actions** required (e.g., technology upgrades, staffing changes, reporting timelines). | Only general categories of deficiencies are listed; no detailed remediation plan is provided. |\n| **Duration of the consent‑order compliance period** (e.g., how many months/years the entities must remain under heightened oversight). | Not mentioned in any excerpt. |\n| **Outcome or current status** (whether the entities have successfully completed the consent‑order requirements). | No follow‑up information is present. |\n| **Impact on customers or third‑party money‑services‑business partners** (e.g., termination of correspondent relationships). | No details are given. |\n| **Whether the entities are classified as “money‑services businesses”** under FinCEN definitions, or are traditional banks with MSB‑like functions. | The excerpts refer to banks; no explicit MSB classification is provided. |\n\n---\n\n### 5. Conclusions Drawn Directly from the Public‑Record Excerpts  \n\n1. **Regulatory Enforcement** – Both AmSouth Bancorporation and Fulton Financial Corporation (through three of its banking subsidiaries) have been subject to formal consent orders for violations of BSA/AML requirements.  \n2. **Scope of Deficiencies** – The regulators identified systemic weaknesses across AML policies, customer due‑diligence, fraud detection, internal controls, and management oversight.  \n3. **Legal Stance** – The entities entered into consent agreements that **neither admit nor deny** the substantive findings (aside from limited jurisdictional admissions).  \n4. **Financial Penalty** – At least one civil money penalty was assessed (AmSouth), though the amount is not disclosed.  \n5. **Ongoing Risk** – Fulton’s filing signals that additional subsidiaries could face separate enforcement actions, indicating a broader, organization‑wide compliance risk.  \n\nAll statements above are **directly supported** by the cited excerpts and no external speculation has been introduced.",
      "citations": [
        "sec-edgar-0000891836-04-000358:ex_99-3.htm",
        "sec-edgar-0000891836-04-000358:ex_99-4.htm",
        "sec-edgar-0001193125-14-336772:d785965d8k.htm",
        "sec-edgar-0001193125-14-455473:d841938d8k.htm",
        "sec-edgar-0001193125-14-272341:d761329d8k.htm"
      ],
      "tokenUsage": {
        "input_tokens": 1128,
        "output_tokens": 1592,
        "reasoning_tokens": 103,
        "total_tokens": 2720,
        "latency_seconds": 3.8
      },
      "sources": [
        {
          "index": 1,
          "docId": "sec-edgar-0000891836-04-000358:ex_99-3.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — AMSOUTH BANCORPORATION  (CIK 0000003133)",
          "url": "https://www.sec.gov/Archives/edgar/data/3133/000089183604000358/ex_99-3.htm",
          "excerpt": ". 208.62 and 208.63); WHEREAS, in order to ensure that AmSouth and the Bank fully address all deficiencies in the Bank’s AML policies and procedures, customer due diligence practices, fraud detection program, internal control environment, management oversight, and responses to law enforcement and regulatory requests, the Board of Governors, AmSouth, and the Bank have mutually agreed to enter into this combined consent Cease and Desist Order and Order of Assessment of a Civil Money Penalty (the",
          "cited": true
        },
        {
          "index": 2,
          "docId": "sec-edgar-0001193125-14-336772:d785965d8k.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — FULTON FINANCIAL CORP  (FULT, FULTP)  (CIK 0000700564)",
          "url": "https://www.sec.gov/Archives/edgar/data/700564/000119312514336772/d785965d8k.htm",
          "excerpt": ". As previously disclosed, on July 14, 2014, three of the Corporation’s other subsidiaries, Fulton Bank, N.A., Swineford National Bank and FNB Bank, N.A., each entered into a Stipulation and Consent to the Issuance of a Consent Order with the Office of the Comptroller of the Currency (the “OCC”), consenting to the issuance by the OCC of a Consent Order (collectively, the “Consent Orders”) with respect to BSA/AML Requirements and the Corporation’s BSA/AML Compliance Program",
          "cited": true
        },
        {
          "index": 3,
          "docId": "sec-edgar-0001193125-14-455473:d841938d8k.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — FULTON FINANCIAL CORP  (FULT, FULTP)  (CIK 0000700564)",
          "url": "https://www.sec.gov/Archives/edgar/data/700564/000119312514455473/d841938d8k.htm",
          "excerpt": ". As previously disclosed, on July 14, 2014, three of the Corporation’s other banking subsidiaries, Fulton Bank, N.A., Swineford National Bank and FNB Bank, N.A., each entered into a Stipulation and Consent to the Issuance of a Consent Order with the Office of the Comptroller of the Currency (the “OCC”), consenting to the issuance by the OCC of a Consent Order (collectively, the “OCC Consent Orders”) with respect to the BSA/AML Requirements and the BSA/AML Compliance Program",
          "cited": true
        },
        {
          "index": 4,
          "docId": "sec-edgar-0000891836-04-000358:ex_99-4.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — AMSOUTH BANCORPORATION  (CIK 0000003133)",
          "url": "https://www.sec.gov/Archives/edgar/data/3133/000089183604000358/ex_99-4.htm",
          "excerpt": ". In order to resolve this matter, and only for that purpose, AmSouth Bank (“AmSouth”) has entered into a CONSENT TO THE ASSESSMENT OF CIVIL MONEY PENALTY (“CONSENT”) dated October 12, 2004, without admitting or denying FinCEN’s determinations described in Sections III and IV below, except as to jurisdiction in Section II below, which is admitted. The CONSENT is incorporated into this ASSESSMENT OF CIVIL MONEY PENALTY (“ASSESSMENT”) by this reference. II",
          "cited": true
        },
        {
          "index": 5,
          "docId": "sec-edgar-0001193125-14-272341:d761329d8k.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — FULTON FINANCIAL CORP  (FULT, FULTP)  (CIK 0000700564)",
          "url": "https://www.sec.gov/Archives/edgar/data/700564/000119312514272341/d761329d8k.htm",
          "excerpt": ". Further, because the Consent Orders and the anticipated Cease and Desist Order relate to the BSA/AML Compliance Program, which is operated jointly for all of the Corporation’s subsidiary banks, the Corporation anticipates that one or more of the Corporation’s other subsidiary banks may also become the subject or subjects of a regulatory enforcement action related to the BSA/AML Requirements, and the provisions of any such enforcement action may differ from those of the Consent Orders",
          "cited": true
        }
      ]
    },
    {
      "query": "digital asset exchange under regulatory investigation for compliance failures",
      "recordedAt": "20260918",
      "report": "**Structured OSINT Report – Digital‑Asset Exchanges Under Regulatory Scrutiny for Compliance Failures**  \n\n---\n\n### 1. Executive Summary  \nThe public‑record excerpts supplied relate primarily to two publicly‑traded entities that reference digital‑asset activities:\n\n| Entity (as referenced in filings) | Primary focus in excerpts |\n|-----------------------------------|---------------------------|\n| **Silvergate Capital Corp.** (Silvergate Exchange Network – SEN) | Statements on risk‑management, compliance posture, and filing of Suspicious Activity Reports (SARs). |\n| **Riot Blockchain, Inc.** | Disclosure of plans to develop a U.S.–based digital‑currency exchange. |\n| **BankAtlantic Bancorp** (included for context) | Description of a compliance‑monitoring framework for BSA (Bank Secrecy Act) compliance. |\n\nThe excerpts do **not** contain a formal regulatory finding, enforcement action, or detailed description of specific compliance failures. They consist of corporate self‑descriptions of risk‑management practices and future business plans.\n\n---\n\n### 2. Detailed Findings  \n\n#### 2.1. Silvergate Capital Corp. – Operational and Compliance Assertions  \n\n| Claim | Source |\n|-------|--------|\n| Silvergate emphasizes that its **Silvergate Exchange Network (SEN)** “has continued to operate uninterrupted” and that the firm provides “dollar deposits when they need them.” | 【1】 |\n| The company states that it “takes risk management and compliance extremely seriously” and that it has “robust risk management controls.” | 【1】 |\n| Silvergate says that when it detects “activity that is unexpected or potentially concerning in any account,” it **investigates** the matter and, when required, **confidentially files a Suspicious Activity Report (SAR)** in accordance with federal regulation. | 【2】 |\n| The filing asserts that Silvergate possesses a “resilient balance sheet and ample liquidity” and that “customers’ deposits are… safely held.” | 【2】 |\n| No explicit mention is made of a regulatory investigation, enforcement action, or identified compliance deficiencies. | — (absence of such language in the excerpts) |\n\n#### 2.2. Riot Blockchain, Inc. – Planned Digital‑Currency Exchange  \n\n| Claim | Source |\n|-------|--------|\n| Riot’s filing references a **“Development of a U.S.-Based Digital Currency Exchange.”** This appears in the Management’s Discussion and Analysis (MD&A) sections of two separate 10‑Q/A filings. | 【3】, 【5】 |\n| The excerpts do not provide any detail on the exchange’s regulatory status, compliance framework, or any investigations. | — (absence of such language) |\n\n#### 2.3. BankAtlantic Bancorp – Compliance Framework (Contextual)  \n\n| Claim | Source |\n|-------|--------|\n| The excerpt outlines components of the bank’s **BSA compliance monitoring** program, including fraud control, authority to correct deficiencies, independent reporting structure, and risk‑based evaluation of transactions, accounts, products, services, and geographic areas. | 【4】 |\n| This information is not directly linked to a digital‑asset exchange but illustrates a typical compliance architecture that a regulated financial institution might employ. | — |\n\n---\n\n### 3. Assessment of Regulatory Investigation / Compliance Failure Indicators  \n\n| Indicator | Presence in Excerpts | Interpretation |\n|-----------|----------------------|----------------|\n| **Explicit regulatory investigation** (e.g., SEC or FinCEN inquiry, formal notice) | **Absent** – no language indicating an ongoing investigation or enforcement proceeding. | The excerpts do not confirm that any of the entities are currently under a regulatory probe. |\n| **Identified compliance failures or deficiencies** | **Absent** – the filings contain only self‑descriptions of compliance programs and risk controls. | No specific failures are disclosed. |\n| **Filing of SARs** | **Present** – Silvergate states it files SARs when required. | Indicates compliance with BSA reporting obligations, but does not imply a failure. |\n| **Liquidity or solvency concerns** | **Addressed** – Silvergate asserts a “resilient balance sheet and ample liquidity.” | This is a defensive statement; no external assessment is provided. |\n| **Future exchange development** | **Present** – Riot plans a U.S. digital‑currency exchange. | No regulatory status or compliance details are given. |\n\n**Conclusion:** Based solely on the supplied excerpts, there is **no direct evidence** of a regulatory investigation or documented compliance failures for the digital‑asset exchange activities described. The documents consist of corporate assurances of compliance and strategic intent.\n\n---\n\n### 4. Gaps & Limitations  \n\n| Missing Information | Reason for Gap |\n|---------------------|----------------|\n| **Formal regulatory findings, cease‑and‑desist orders, or enforcement actions** | Not referenced in any of the excerpts. |\n| **Specific compliance deficiencies (e.g., AML/BSA lapses, internal control weaknesses)** | The excerpts only contain generic statements about risk management and SAR filing. |\n| **Details on the operational scope, customer base, or transaction volumes of the exchanges** | Not disclosed in the provided text. |\n| **Independent third‑party assessments or audit results** | No such material is included. |\n| **Status of Riot’s planned exchange (e.g., licensing, regulatory approvals)** | The excerpts merely note the intent to develop an exchange. |\n\n---\n\n### 5. Recommendations for Further Research  \n\n1. **Search for additional SEC filings** (e.g., 8‑K, 10‑K, 10‑Q) that may contain **Risk Factors** or **Legal Proceedings** sections referencing regulatory actions.  \n2. **Review FinCEN and state‑level regulator databases** for any public notices involving the entities.  \n3. **Examine news releases and press statements** post‑date of the excerpts for any announced investigations or penalties.  \n4. **Obtain the full 8‑K and 10‑Q documents** referenced (beyond the excerpted paragraphs) to capture any omitted sections that discuss compliance matters.  \n\n---\n\n**Prepared by:** OSINT Analyst (entity‑category focus)  \n**Date:** 2026‑09‑18  \n\n*All factual statements are directly sourced from the provided excerpts and are cited accordingly.*",
      "citations": [
        "sec-edgar-0001312109-22-000233:ex991-letterfromsilvergate.htm",
        "sec-edgar-0001079973-19-000116:riot_10qa2-093018.htm",
        "sec-edgar-0001079973-19-000014:riot_10qa-093018.htm",
        "sec-edgar-0000950144-06-004051:g01079exv10w4.htm"
      ],
      "tokenUsage": {
        "input_tokens": 1006,
        "output_tokens": 1430,
        "reasoning_tokens": 120,
        "total_tokens": 2436,
        "latency_seconds": 3.31
      },
      "sources": [
        {
          "index": 1,
          "docId": "sec-edgar-0001312109-22-000233:ex991-letterfromsilvergate.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — Silvergate Capital Corp  (SICP)  (CIK 0001312109)",
          "url": "https://www.sec.gov/Archives/edgar/data/1312109/000131210922000233/ex991-letterfromsilvergate.htm",
          "excerpt": ". dollar deposits when they need them and that the Silvergate Exchange Network (“SEN”) has continued to operate uninterrupted throughout this period. I wanted to take this opportunity to set the record straight about Silvergate’s role in the digital asset ecosystem and what we have always done, and continue to do, to ensure our customers act in accordance with our robust risk management controls. We take risk management and compliance extremely seriously",
          "cited": true
        },
        {
          "index": 2,
          "docId": "sec-edgar-0001312109-22-000233:ex991-letterfromsilvergate.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — Silvergate Capital Corp  (SICP)  (CIK 0001312109)",
          "url": "https://www.sec.gov/Archives/edgar/data/1312109/000131210922000233/ex991-letterfromsilvergate.htm",
          "excerpt": ". And, as I’ve noted previously, if we detect activity that is unexpected or potentially concerning in any account, we conduct an investigation and, when required, confidentially file a suspicious activity report in accordance with federal regulation. We have a resilient balance sheet and ample liquidity. While this has been a turbulent time in the digital asset industry, our customers’ deposits are, and have always been, safely held",
          "cited": true
        },
        {
          "index": 3,
          "docId": "sec-edgar-0001079973-19-000116:riot_10qa2-093018.htm",
          "source": "SEC_EDGAR",
          "title": "10-Q/A — Riot Blockchain, Inc.  (RIOT)  (CIK 0001167419)",
          "url": "https://www.sec.gov/Archives/edgar/data/1167419/000107997319000116/riot_10qa2-093018.htm",
          "excerpt": ". Part I, Item 2 – Management’s Discussion and Analysis of Results of Operations and Financial Condition, Management’s plans and basis of presentation; Digital Currencies Translations and Remeasurements; iii. Part I, Item 2 – Management’s Discussion and Analysis of Results of Operations and Financial Condition, Management’s plans and basis of presentation: Development of a U.S.-Based Digital Currency Exchange; iv",
          "cited": true
        },
        {
          "index": 4,
          "docId": "sec-edgar-0000950144-06-004051:g01079exv10w4.htm",
          "source": "SEC_EDGAR",
          "title": "8-K — BANKATLANTIC BANCORP INC  (CIK 0000921768)",
          "url": "https://www.sec.gov/Archives/edgar/data/921768/000095014406004051/g01079exv10w4.htm",
          "excerpt": "in fraud control and compliance monitoring; (iv) authority to correct identified deficiencies; (v) reporting structure and independence from Bank Management; (vi) the Bank’s methodology for collecting, maintaining, and recalling information related to transactions that pose greater than normal risks for BSA compliance; and (vii) evaluation of the types of transactions, accounts, products, services, and geographic areas that pose greater than normal risks for compliance with the BSA Compliance",
          "cited": true
        },
        {
          "index": 5,
          "docId": "sec-edgar-0001079973-19-000014:riot_10qa-093018.htm",
          "source": "SEC_EDGAR",
          "title": "10-Q/A — Riot Blockchain, Inc.  (RIOT)  (CIK 0001167419)",
          "url": "https://www.sec.gov/Archives/edgar/data/1167419/000107997319000014/riot_10qa-093018.htm",
          "excerpt": ". Part I, Item 2 – Management's Discussion and Analysis of Results of Operations and Financial Condition, Management's plans and basis of presentation; Digital Currencies Translations and Remeasurements; iii. Part I, Item 2 – Management's Discussion and Analysis of Results of Operations and Financial Condition, Management's plans and basis of presentation: Development of a U.S.-Based Digital Currency Exchange; iv",
          "cited": true
        }
      ]
    }
  ]
} as const;
